### ISSUE TITLE
Use server time

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#12]
I ran into a situation where my local clock got ahead of the servers which lead to an error response on all my requests:
`{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}`

Wondering if there's a means to say "use server time" in the library by keeping a delta to local time...

**Comment by luzzif** [comment]
There's nothing that prevents errors like this to happen, and I personally think it should stay like this. Timing issues are usually VERY hard to find/fix, so it's better not to introduce anything time-related to the package, just to be safe about the topic. It's the users' responsibility to make sure that their local time is synced with the Binance's server time. Thanks anyway for the observation!
