### ISSUE TITLE
Client project Sample

### ISSUE THREAD

**Issue by fhunth** [luzzif/binance-api-client#15]
Could you add a simple project to the solution? A kind of simple windows form with a call to a method.
Thanks

**Comment by luzzif** [comment]
First of all, thanks for stopping by but... isn't the documentation enough? The library is overall very simple to use and I don't think you need to see from me how to gather data from a form in order to call the library since you most probably should already know it.

**Comment by gemmell** [comment]
It's a typescript library, there is no windows form that can possibly go along with it. If you need something a little less hands-on check out Profit Trailer.

**Comment by luzzif** [comment]
Closing as the library is simple enough to pick up without a sample.
