### ISSUE TITLE
Dubious user stream quality

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#16]
I'm getting this scenario where I just seem to not get any more user stream messages after some amount of time. e.g. I'm putting in buy limit order, it's getting bought, but I don't receive any user update about it. The ws has not disconnected however.

Reading the docs it says:
`A User Data Stream listenKey is valid for 60 minutes after creation.`
`Doing a PUT on a listenKey will extend its validity for 60 minutes.`

I can't see the library doing that `put`, so I'm willing to bet that after 1 hour the server is simply not sending any more data on that websocket, even though it is still connected. 

Suggest adding a setTimeout that does a `put` every 30 minutes or so.

**Comment by gemmell** [comment]
Yeah, looking at `binance-api-node` they do `const int = setInterval(keepStreamAlive(keepDataStream, listenKey), 50e3)
    keepStreamAlive(keepDataStream, listenKey)()`

**Comment by gemmell** [comment]
Ah, I just found `keepAliveUserStream` - am I supposed to call that myself?

**Comment by gemmell** [comment]
I know you're just trying to wrap the API and not much more, but that has cost me a bunch of money because it's not at all clear that it needs to be done. Perhaps include another parameter to `monitorUser` called `sendKeepAlivePut` or something so that it's explicitly handled for you by the library (similar to the heartbeat).

**Comment by luzzif** [comment]
As previously said, I really want the library to not have much other than the ability to interact with the Binance's API, so that when you use it, the Binance documentation should tell you all there is to know. In this specific case, a simple setTimeout will suffice, and I won't include it into the code.

**Comment by gemmell** [comment]
You should at the very least put it in the documentation for the `monitorUser` function.

**Comment by luzzif** [comment]
You are right about that, in fact I updated the documentation in the latest version (2.5.2). Thanks again!
