### ISSUE TITLE
Order Update numbers are strings 

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#17]
I've run into this problem a couple of times: The float values that come back from binance JSON are strings not numbers. Despite typescript being there and despite it saying that they are numbers, they still can end up strings. As such I've had various scenario's where I've done something like `update.price + 0.001` and ended up with `0.00580.001`. 

Suggest you wrap everything in `parseFloat` for the OrderUpdate.ts 
Also last executed quantity is missing from the structure:
`  "l": "0.00000000",             // Last executed quantity`

**Comment by gemmell** [comment]
I've added them in my clone if you just want to cherry pick it.

**Comment by luzzif** [comment]
Fixed in 2.6.0. Thank you very much for the on-point contribution.

**Comment by gemmell** [comment]
I just took a look at some of the other messages - they're all the same. So you might want to run through all your message data classes and add the parseFloat where necessary. If you don't, I'll get to it eventually :)
