### ISSUE TITLE
Almost certain user stream stops working

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#18]
I am almost certain that the user stream stops working
My code looks like this:
```
const userKey: string = await binance.openUserStream();
  await binance.monitorUser(
    userKey,
    (update: AccountUpdate | OrderUpdate) => {
      if (update instanceof AccountUpdate) {
        wallet.updateBalances(update);
      } else if (update instanceof OrderUpdate) {
        for (const trader of traders) {
          trader.orderUpdate(update as OrderUpdate);
        }
      }
    },
    streamHeartbeatTimeout,
    () => {
      console.log("Reconnecting to user stream");
      subscribeToUserStream(wallet);
    },
  );
  console.log("Opened user stream " + userKey);
  setInterval(() => {
    console.log(new Date() + " Sending PUT on user stream");
    binance.keepAliveUserStream(userKey);
  }, 15 * 60 * 1000);
```
So it should be sending the PUT every 15 minutes. However after some unknown amount of time, it stops getting any updates. There is no reconnection going on, so its not that.

**Comment by gemmell** [comment]
So I changed things up. Quite possible this is not an issue with your library, but something that users will need to be aware of.

I looked at some other libraries implementation of the keep alive: They send the PUT every 50 seconds. I have since changed my PUT keepAlive to 50 seconds and it's been over 12 hours and i'm still getting user events. So perhaps 15 minutes was just the wrong value to use and the internal timings of binance stop sending user events if they don't get a put within say 15 minutes (and if so, I would have been right on the cusp which would explain why occasionally I drop - binance just stops sending me messages). I also reduced my stream heartbeat timeout from 10 minutes to 20 minutes, the docs recommend 30 minutes.

**Comment by luzzif** [comment]
That's some really good news. I doubted this was a problem with the library myself, but it's strange because having a look at the [official Binance's doc](https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#general-wss-information), the key validity is set to 60 minutes. Either way, thanks for the contribution.
