### ISSUE TITLE
Possibility for cors

### ISSUE THREAD

**Issue by DomEscobar** [luzzif/binance-api-client#2]
Hey very nice work,
could you implement a methode for people without a nginx orElse to pass cors.

```
let apiUrl: URL = new URL(
            Path.join( "/api", apiVersion, accessedResource ),
           --https://cors-anywhere.herokuapp.com/-- "https://api.binance.com"
        );
```

**Comment by luzzif** [comment]
Man I gotta be honest, I don't understand what you want, but if you provide your own implementation through a PR, I'll be happy to review it :smile:

**Comment by luzzif** [comment]
PR provided, reviewed but not ready to merge. No feedback in a long time, closing.
