### ISSUE TITLE
TypeError: url_1.URL is not a constructor

### ISSUE THREAD

**Issue by erdenemunkh** [luzzif/binance-api-client#3]
I have one problem is TypeError: url_1.URL is not a constructor;

How to solve this problem? 

Thanks

**Comment by luzzif** [comment]
Try upping your Node version to ^8.4.0, it should work.

**Comment by erdenemunkh** [comment]
Thank you for replay.

I am installed node latest version 8.9.4. Still not working same error.

my code is here

![sc_binnance](https://user-images.githubusercontent.com/2663352/35605331-270f7784-0683-11e8-8454-6ae00c89817c.PNG)


Screenshot is here

![tradebot error](https://user-images.githubusercontent.com/2663352/35605281-b601c07e-0682-11e8-8cb1-65864e5054e2.PNG)

**Comment by luzzif** [comment]
Could you please provide a ready-to-test repository exactly replicating the issue?

**Comment by erdenemunkh** [comment]
https://github.com/erdenemunkh/BinanceTraderBot/blob/master/src/pages/home/home.ts

**Comment by luzzif** [comment]
After searching a bit around, it seems to be a problem with webpack itself, but I'm sorry I can't say much about it... I'm leaving this open in case someone can solve this.

**Comment by DomEscobar** [comment]
https://github.com/webpack/node-libs-browser/issues/69
