### ISSUE TITLE
Filters not initialised

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#7]
In ExchangeInfo.ts the `switch` statement doesn't include all of the available types of filter and there is no `default`. So if it's not either a `EXCHANGE_MAX_NUM_ORDERS` or `EXCHANGE_MAX_ALGO_ORDERS` then it gets pushed into `this._filters` as an `undefined`.

Ideally I would like a convenience function that uses the filter information to turn a `quantity` and `price` in one token into a tradeable amount in another. e.g. `qtyForPrice(symOne: "ETH", qty: 1.0, symTwo: "POWER", price: 0.001) ` which returns a quantity of POWER that obeys the rules for trading quantity.

**Comment by luzzif** [comment]
The filter mapping issue should be fixed as of version 2.4.0. About the utility function, I'd like this library to simply act as an interface to Binance, so no logic should be incorporated in it.
