### ISSUE TITLE
Better error handling when things go awry

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#8]
The `getAccountData` function is failing with the error 
`TypeError: json.balances is not iterable
    at new AccountData (c:\tkbt\ML\COINVOL\bigdipper2\node_modules\binance-api-client\src\models\account\AccountData.ts:28:34)
`

I put a `console.log` in there and it's actually getting 
`{ code: -1021,
  msg: 'Timestamp for this request was 1000ms ahead of the server\'s time.' }`

However there's no error handling going on and it's trying to assign internal variables anyway.

**Comment by gemmell** [comment]
In a similar vein, if I try to do a `binance.placeOrder` which contravene's their filters (e.g. `await binance.placeOrder("ARKETH", OrderSide.BUY, OrderType.LIMIT, TimeInForce.GTC, 12, 0.00441784);` the result is just a bunch of undefineds - there's no throwing of errors.

**Comment by luzzif** [comment]
Both issues should have been fixed in version 2.3.0.
