### ISSUE TITLE
STOP_LOSS orders require you to not send timeInForce

### ISSUE THREAD

**Issue by gemmell** [luzzif/binance-api-client#9]
Currently `buy` requires a `timeInForce`, but actually if you you send a `STOP_LOSS` you'll get 
`{"code":-1106,"msg":"Parameter 'timeInForce' sent when not required."}` because for STOP_LOSS you're not supposed to send timeInForce.

**Comment by gemmell** [comment]
Same for price: `{"code":-1106,"msg":"Parameter 'price' sent when not required."}`

**Comment by luzzif** [comment]
Should be fixed in version 2.2.1.
